---
name: 友链申请
about: 申请将你的网站添加为友链。请完整填写下列信息以便自动创建友链文件并通过审核。
title: "[友链申请] {网站名称}"
labels:
  - friend-link
assignees: []
body: |
  ## 友链信息（请在下面填写或补充）

  - **网站名称**：
  - **网站地址**（请使用 HTTPS 优先）：
  - **网站描述**（一句话介绍）：
  - **头像地址**（可为完整图片 URL）：
  - **你的短名称**（用于文件名，仅限英文字母和数字，例如：geekertao）：

  ## 其他说明
  - 必须符合中华人民共和国相关法律法规，不能包含任何违法或不当内容。
  - 推荐启用 HTTPS 协议，确保网站安全。
  - 请确保网站内容健康、积极向上，便于通过审核。

  ---
  **注意**
  1. 提交申请后，GitHub Actions 会自动创建友链文件。
  2. 审核通过后，你的友链将会展示在友链页面。
  3. 若信息不完整或需进一步核实，维护者会在此 issue 中与您联系。
