# .github/ISSUE_TEMPLATE/friend-link.yml
name: 友链申请
description: 申请将你的网站添加为友链
title: "[友链] "
labels: ["friend-link"]
body:
  - type: input
    id: name
    attributes:
      label: 网站名称
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: 网站地址
      description: 必须使用 HTTPS
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: 网站描述
      description: 一句话介绍
    validations:
      required: true

  - type: input
    id: avatar
    attributes:
      label: 头像地址
      description: 图片 URL
    validations:
      required: true

  - type: input
    id: shortname
    attributes:
      label: 短名称
      description: 用于文件名，仅限字母、数字、下划线、连字符
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 其他说明
        - 必须符合中华人民共和国相关法律法规
        - 推荐启用 HTTPS 协议
        - 请确保网站内容健康、积极向上
