name: 友链申请
description: 申请将你的网站添加为友链
title: "[友链申请] "
labels: ["friend-link"]
body:
  - type: input
    id: name
    attributes:
      label: 网站名称
      placeholder: 例如：技术咖啡馆
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: 网站地址
      description: 请使用 HTTPS 协议
      placeholder: https://example.com
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 网站描述
      placeholder: 一句话介绍你的网站
    validations:
      required: true

  - type: input
    id: avatar
    attributes:
      label: 头像地址
      placeholder: https://example.com/avatar.png

  - type: input
    id: shortname
    attributes:
      label: 短名称
      description: 用于文件名，仅限英文字母和数字
      placeholder: geekertao
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 其他说明
        - 必须符合中华人民共和国相关法律法规
        - 推荐启用 HTTPS 协议
        - 请确保网站内容健康、积极向上