---
name: 友链申请
about: 申请添加友链
title: '[友链申请] '
labels: ['friend-link']
assignees: []
---

## 友链信息

请填写以下信息：

- **网站名称**：
- **网站地址**：
- **网站描述**（一句话介绍）：
- **头像地址**：
- **你的短名称**（用于文件名，仅限英文字母和数字，如：geekertao）：

## 其他说明

必须符合中华人民共和国相关法律法规，不能包含任何违法内容。
推荐启用HTTPS协议，确保网站安全。

---

**注意**：
1. 提交申请后，GitHub Actions 会自动创建友链文件
2. 审核通过后，你的友链将会展示在友链页面
3. 请确保你的网站内容健康、积极向上
